openapi: 3.0.0
info:
  title: CharVstack-API
  version: "1.0"
servers:
- url: http://localhost:3000/api/v1
tags:
- name: vm
paths:
  /vms:
    get:
      operationId: get-api-v1-vms
      responses:
        "200":
          content:
            application/json:
              examples:
                example-1:
                  value:
                    vms:
                    - name: ubuntu20.04
                      metadata:
                        id: v1
                        api_version: 4e0a3c48-f483-422a-b520-2820207cef42
                      memory: 2048
                      vcpu: 4
                      devices:
                        disk:
                        - type: qcow2
                          path: /var/lib/libvirt/images/ubuntu22.04.qcow2
              schema:
                $ref: '#/components/schemas/get_api_v1_vms_200_response'
          description: OK
      summary: Get all VMs list
      tags:
      - vm
    post:
      operationId: post-api-v1-vms
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  name: ubuntu20.04
                  memory: 2048
                  vcpu: 4
            schema:
              $ref: '#/components/schemas/post_api_v1_vms_request'
      responses:
        "200":
          description: OK
      summary: Create a new VM
      tags:
      - vm
  /vms/{vmId}:
    get:
      operationId: get-api-v1-vms-vmId
      parameters:
      - explode: false
        in: path
        name: vmId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              examples:
                example-1:
                  value:
                    name: ubuntu20.04
                    metadata:
                      id: v1
                      api_version: 4e0a3c48-f483-422a-b520-2820207cef42
                    memory: 2048
                    vcpu: 4
                    devices:
                      disk:
                      - type: qcow2
                        path: /var/lib/libvirt/images/ubuntu22.04.qcow2
              schema:
                $ref: '#/components/schemas/vm'
          description: OK
      summary: Get a VM
      tags:
      - vm
    patch:
      operationId: patch-api-v1-vms-vmId
      parameters:
      - explode: false
        in: path
        name: vmId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            examples:
              example-1:
                value:
                  name: centos_stream
                  memory: 1024
                  vcpu: 2
            schema:
              $ref: '#/components/schemas/patch_api_v1_vms_vmId_request'
      responses:
        "200":
          description: OK
      summary: Update a VM
      tags:
      - vm
  /host:
    get:
      operationId: get-api-v1-host
      responses:
        "200":
          content:
            application/json:
              examples:
                example-1:
                  value:
                    cpu:
                      cpu: 4
                      cpu_mhz: 0
                    mem:
                      total: 2048
                      used: 0
                      free: 0
                      used_percent: 20
                    storage_pools:
                    - name: default
                      total_size: 20000
                      used_size: 10000
                      path: /var/lib/libvirt/images
                      status: active
              schema:
                $ref: '#/components/schemas/get_api_v1_host_200_response'
          description: OK
      summary: Get a host
      tags:
      - host
components:
  schemas:
    vm:
      description: ""
      example:
        metadata:
          id: id
          api_version: api_version
        memory: 0
        vcpu: 6
        devices:
          disk:
          - path: path
            type: type
          - path: path
            type: type
        name: name
      properties:
        name:
          type: string
        metadata:
          $ref: '#/components/schemas/vm_metadata'
        memory:
          type: integer
        vcpu:
          type: integer
        devices:
          $ref: '#/components/schemas/vm_devices'
      title: vm
      type: object
      x-stoplight:
        id: 5txew3qu80ak2
      x-tags:
      - vm
    cpu:
      example:
        cpu: 0
        cpu_mhz: 6.027456183070403
      properties:
        cpu:
          type: integer
        cpu_mhz:
          type: number
      title: cpu
      type: object
      x-stoplight:
        id: fph02iclwns7j
      x-tags:
      - host
    memory:
      example:
        total: 1
        used_percent: 2.3021358869347655
        used: 5
        free: 5
      properties:
        total:
          type: integer
        used:
          type: integer
        free:
          type: integer
        used_percent:
          type: number
      title: memory
      type: object
      x-stoplight:
        id: dgl6tqiyb7itd
      x-tags:
      - host
    storage_pool:
      example:
        path: path
        name: name
        total_size: 7
        used_size: 9
        status: status
      properties:
        name:
          type: string
        total_size:
          type: integer
        used_size:
          type: integer
        path:
          type: string
        status:
          type: string
      title: storage_pool
      type: object
      x-stoplight:
        id: aeklue11tdj8x
      x-tags:
      - host
    get_api_v1_vms_200_response:
      example:
        vms:
        - metadata:
            id: id
            api_version: api_version
          memory: 0
          vcpu: 6
          devices:
            disk:
            - path: path
              type: type
            - path: path
              type: type
          name: name
        - metadata:
            id: id
            api_version: api_version
          memory: 0
          vcpu: 6
          devices:
            disk:
            - path: path
              type: type
            - path: path
              type: type
          name: name
      properties:
        vms:
          items:
            $ref: '#/components/schemas/vm'
          type: array
      type: object
    post_api_v1_vms_request:
      properties:
        name:
          type: string
        memory:
          type: integer
        vcpu:
          type: integer
      required:
      - memory
      - name
      - vcpu
      type: object
    patch_api_v1_vms_vmId_request:
      properties:
        name:
          type: string
        memory:
          type: integer
        vcpu:
          type: integer
      type: object
    get_api_v1_host_200_response:
      example:
        storage_pools:
        - path: path
          name: name
          total_size: 7
          used_size: 9
          status: status
        - path: path
          name: name
          total_size: 7
          used_size: 9
          status: status
        mem:
          total: 1
          used_percent: 2.3021358869347655
          used: 5
          free: 5
        cpu:
          cpu: 0
          cpu_mhz: 6.027456183070403
      properties:
        cpu:
          $ref: '#/components/schemas/cpu'
        mem:
          $ref: '#/components/schemas/memory'
        storage_pools:
          items:
            $ref: '#/components/schemas/storage_pool'
          type: array
      type: object
    vm_metadata:
      example:
        id: id
        api_version: api_version
      properties:
        id:
          type: string
        api_version:
          type: string
      type: object
    vm_devices_disk_inner:
      example:
        path: path
        type: type
      properties:
        type:
          type: string
        path:
          type: string
      type: object
    vm_devices:
      example:
        disk:
        - path: path
          type: type
        - path: path
          type: type
      properties:
        disk:
          items:
            $ref: '#/components/schemas/vm_devices_disk_inner'
          type: array
      type: object
x-stoplight:
  id: 291epccbgj72d
